version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.1.0

jobs:
  main:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo
    steps:
#      - setup_remote_docker:
#          docker_layer_caching: true
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
#      - aws-ecr/build-and-push-image:
#          repo: dbt-serverless
#          tag: latest
#      - aws-ecr/build-and-push-image:
#          repo: dbt-serverless
#          tag: ${CIRCLE_SHA1}


workflows:
  version: 2
  flow:
    jobs:
      - main
